export const internationalDeliveryCalculatorData = {
  deliveryAreas: [
    "India",
    "China",
    "Nepal",
    "USA",
    "Bhutan",
    "London",
    "Afghanisthan",
    "Srilanka",
    "Russia",
  ],

  parcelWeights: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  prices: {
    1: 500,
    2: 700,
    3: 900,
    4: 1100,
    5: 1300,
    6: 1500,
    7: 1700,
    8: 1900,
    9: 2100,
    10: 2300,
  },
};

const deliveryCalculatorData = {
  deliveryAreas: [
    "Bagerhat",
    "Bandarban",
    "Barguna",
    "Barisal",
    "Bhola",
    "Bogra",
    "Brahmanbaria",
    "Chandpur",
    "Chapai Nawabganj",
    "Chattogram",
    "Chuadanga",
    "Cox's Bazar",
    "Cumilla",
    "Dhaka",
    "Dinajpur",
    "Faridpur",
    "Feni",
    "Gaibandha",
    "Gazipur",
    "Gopalganj",
    "Habiganj",
    "Jamalpur",
    "Jashore",
    "Jhalokathi",
    "Jhenaidah",
    "Joypurhat",
    "Khagrachari",
    "Khulna",
    "Kishoreganj",
    "Kurigram",
    "Kushtia",
    "Lakshmipur",
    "Lalmonirhat",
    "Madaripur",
    "Magura",
    "Manikganj",
    "Meherpur",
    "Moulvibazar",
    "Munshiganj",
    "Mymensingh",
    "Naogaon",
    "Narail",
    "Narayanganj",
    "Narsingdi",
    "Natore",
    "Netrokona",
    "Nilphamari",
    "Noakhali",
    "Pabna",
    "Panchagarh",
    "Patuakhali",
    "Pirojpur",
    "Rajbari",
    "Rajshahi",
    "Rangamati",
    "Rangpur",
    "Satkhira",
    "Shariatpur",
    "Sherpur",
    "Sirajganj",
    "Sunamganj",
    "Sylhet",
    "Tangail",
    "Thakurgaon",
  ],
  zones: {
    Dhaka: ["Dhaka"],
    SubDhaka: ["Narayanganj", "Gazipur"],
    OutsideDhaka: [
      "Bagerhat",
      "Bandarban",
      "Barguna",
      "Barisal",
      "Bhola",
      "Bogra",
      "Brahmanbaria",
      "Chandpur",
      "Chapai Nawabganj",
      "Chattogram",
      "Chuadanga",
      "Cox's Bazar",
      "Cumilla",
      "Dinajpur",
      "Faridpur",
      "Feni",
      "Gaibandha",
      "Gopalganj",
      "Habiganj",
      "Jamalpur",
      "Jashore",
      "Jhalokathi",
      "Jhenaidah",
      "Joypurhat",
      "Khagrachari",
      "Khulna",
      "Kishoreganj",
      "Kurigram",
      "Kushtia",
      "Lakshmipur",
      "Lalmonirhat",
      "Madaripur",
      "Magura",
      "Manikganj",
      "Meherpur",
      "Moulvibazar",
      "Munshiganj",
      "Mymensingh",
      "Naogaon",
      "Narail",
      "Narsingdi",
      "Natore",
      "Netrokona",
      "Nilphamari",
      "Noakhali",
      "Pabna",
      "Panchagarh",
      "Patuakhali",
      "Pirojpur",
      "Rajbari",
      "Rajshahi",
      "Rangamati",
      "Rangpur",
      "Satkhira",
      "Shariatpur",
      "Sherpur",
      "Sirajganj",
      "Sunamganj",
      "Sylhet",
      "Tangail",
      "Thakurgaon",
    ],
  },
  parcelWeights: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  prices: {
    Dhaka: {
      1: 60,
      2: 90,
      3: 120,
      4: 150,
      5: 180,
      6: 210,
      7: 240,
      8: 270,
      9: 300,
      10: 330,
    },
    SubDhaka: {
      1: 100,
      2: 140,
      3: 180,
      4: 220,
      5: 260,
      6: 300,
      7: 340,
      8: 380,
      9: 420,
      10: 460,
    },
    OutsideDhaka: {
      1: 120,
      2: 160,
      3: 200,
      4: 240,
      5: 280,
      6: 320,
      7: 360,
      8: 400,
      9: 440,
      10: 480,
    },
  },
};

export default deliveryCalculatorData;
